default: true
line-length: false
no-bare-urls: false
no-alt-text: false
ul-style:
  style: dash
heading-style:
  style: atx
ul-indent:
  indent: 2
no-inline-html:
  allowed_elements:
    - small
    - code
    - dl
    - dt
    - dd
    - figure
    - figcaption
    - img
    - ruby
    - rt
    - rp
    - details
    - summary
    - kbd
    - TweetILearned
    - head
    - title
    - iframe
    - br
